-- AlterTable
ALTER TABLE "Finca" ADD COLUMN     "metaAnimales" INTEGER NOT NULL DEFAULT 150,
ADD COLUMN     "precioLibra" DOUBLE PRECISION NOT NULL DEFAULT 85,
ADD COLUMN     "precioReproductora" DOUBLE PRECISION NOT NULL DEFAULT 29000;
