/**
 * Tipos de dispositivos del Smart Farm Hub.
 */

export const DEVICE_TYPE = {
  RFID:              "rfid",
  ARETE:             "arete",
  GPS:               "gps",
  BASCULA:           "bascula",
  SENSOR_TEMP:       "sensor_temp",
  SENSOR_HUMEDAD:    "sensor_humedad",
  SENSOR_LLUVIA:     "sensor_lluvia",
  SENSOR_VIENTO:     "sensor_viento",
  SENSOR_AGUA:       "sensor_agua",
  SENSOR_TANQUE:     "sensor_tanque",
  SENSOR_PASTURA:    "sensor_pastura",
  SENSOR_CERCA:      "sensor_cerca",
  COLLAR:            "collar",
  CAMARA:            "camara",
  DRONE:             "drone",
  ESTACION_METEO:    "estacion_meteo",
  PANEL_SOLAR:       "panel_solar",
  BOMBA:             "bomba",
  CERCA_ELECTRICA:   "cerca_electrica",
};

export const DEVICE_TYPE_CONFIG = {
  rfid: {
    nombre:    "Lector RFID",
    icono:     "📡",
    color:     "#6366f1",
    categoria: "identificacion",
    protocolos: ["bluetooth", "wifi", "usb"],
    campos:    ["lecturas", "animal_id", "eventos"],
    descripcion: "Lee aretes electrónicos e identifica animales automáticamente.",
  },
  arete: {
    nombre:    "Arete Electrónico",
    icono:     "🏷️",
    color:     "#8b5cf6",
    categoria: "identificacion",
    protocolos: ["bluetooth", "lora"],
    campos:    ["animal_id", "codigo_eid", "codigo_vid"],
    descripcion: "Identificador electrónico individual por animal.",
  },
  gps: {
    nombre:    "GPS Tracker",
    icono:     "🛰️",
    color:     "#3b82f6",
    categoria: "ubicacion",
    protocolos: ["4g", "lora", "wifi"],
    campos:    ["lat", "lng", "velocidad", "heading", "altitud"],
    descripcion: "Rastrea ubicación de animales, vehículos o personal.",
  },
  bascula: {
    nombre:    "Báscula Electrónica",
    icono:     "⚖️",
    color:     "#0ea5e9",
    categoria: "produccion",
    protocolos: ["wifi", "bluetooth", "rs232"],
    campos:    ["peso_kg", "animal_id", "fecha"],
    descripcion: "Captura peso automáticamente y actualiza historial.",
  },
  sensor_temp: {
    nombre:    "Sensor de Temperatura",
    icono:     "🌡️",
    color:     "#ef4444",
    categoria: "ambiental",
    protocolos: ["wifi", "lora", "zigbee"],
    campos:    ["temperatura_c", "indice_thi"],
    descripcion: "Monitorea temperatura ambiental y THI (estrés calórico).",
  },
  sensor_humedad: {
    nombre:    "Sensor de Humedad",
    icono:     "💧",
    color:     "#06b6d4",
    categoria: "ambiental",
    protocolos: ["wifi", "lora", "zigbee"],
    campos:    ["humedad_pct", "punto_rocio"],
    descripcion: "Monitorea humedad relativa del ambiente.",
  },
  sensor_lluvia: {
    nombre:    "Pluviómetro",
    icono:     "🌧️",
    color:     "#0284c7",
    categoria: "ambiental",
    protocolos: ["wifi", "lora"],
    campos:    ["lluvia_mm", "lluvia_dia", "lluvia_mes"],
    descripcion: "Mide precipitación acumulada.",
  },
  sensor_viento: {
    nombre:    "Anemómetro",
    icono:     "🌬️",
    color:     "#64748b",
    categoria: "ambiental",
    protocolos: ["wifi", "lora"],
    campos:    ["velocidad_kmh", "direccion_grados"],
    descripcion: "Mide velocidad y dirección del viento.",
  },
  sensor_agua: {
    nombre:    "Sensor de Calidad de Agua",
    icono:     "🧪",
    color:     "#22c55e",
    categoria: "ambiental",
    protocolos: ["wifi", "lora"],
    campos:    ["ph", "turbidez", "conductividad", "temperatura_agua"],
    descripcion: "Monitorea calidad del agua de bebida.",
  },
  sensor_tanque: {
    nombre:    "Sensor de Nivel de Tanque",
    icono:     "🪣",
    color:     "#f59e0b",
    categoria: "infraestructura",
    protocolos: ["wifi", "lora", "zigbee"],
    campos:    ["nivel_pct", "volumen_litros", "capacidad_litros"],
    descripcion: "Monitorea nivel de tanques de agua.",
  },
  sensor_pastura: {
    nombre:    "Sensor de Pastura",
    icono:     "🌿",
    color:     "#16a34a",
    categoria: "produccion",
    protocolos: ["wifi", "lora"],
    campos:    ["altura_cm", "biomasa_kg_ha", "humedad_suelo"],
    descripcion: "Estima disponibilidad forrajera del potrero.",
  },
  sensor_cerca: {
    nombre:    "Sensor de Cerca Eléctrica",
    icono:     "⚡",
    color:     "#eab308",
    categoria: "infraestructura",
    protocolos: ["wifi", "lora"],
    campos:    ["voltaje_v", "corriente_ma", "estado"],
    descripcion: "Monitorea funcionamiento de la cerca eléctrica.",
  },
  collar: {
    nombre:    "Collar Inteligente",
    icono:     "📿",
    color:     "#a855f7",
    categoria: "animal",
    protocolos: ["bluetooth", "lora", "4g"],
    campos:    ["lat", "lng", "pasos", "rumia_min", "temperatura_corporal", "actividad"],
    descripcion: "Monitorea comportamiento, salud y ubicación del animal.",
  },
  camara: {
    nombre:    "Cámara Inteligente",
    icono:     "📷",
    color:     "#6b7280",
    categoria: "vigilancia",
    protocolos: ["wifi", "4g", "ethernet"],
    campos:    ["stream_url", "detecciones", "grabaciones"],
    descripcion: "Vigilancia y detección automática de eventos.",
  },
  drone: {
    nombre:    "Drone",
    icono:     "🚁",
    color:     "#0f172a",
    categoria: "inspeccion",
    protocolos: ["wifi", "4g"],
    campos:    ["lat", "lng", "altitud", "bateria_pct", "mision", "imagenes"],
    descripcion: "Inspección aérea, conteo de ganado y evaluación de potreros.",
  },
  estacion_meteo: {
    nombre:    "Estación Meteorológica",
    icono:     "🌤️",
    color:     "#f97316",
    categoria: "ambiental",
    protocolos: ["wifi", "ethernet", "lora"],
    campos:    ["temperatura_c", "humedad_pct", "lluvia_mm", "velocidad_viento", "presion_hpa", "radiacion_solar"],
    descripcion: "Estación completa de clima local en la finca.",
  },
  panel_solar: {
    nombre:    "Panel Solar / Monitor",
    icono:     "☀️",
    color:     "#fbbf24",
    categoria: "energia",
    protocolos: ["wifi", "modbus"],
    campos:    ["potencia_w", "energia_dia_kwh", "voltaje_v", "temperatura_panel"],
    descripcion: "Monitorea generación y consumo de energía solar.",
  },
  bomba: {
    nombre:    "Controlador de Bomba",
    icono:     "🔧",
    color:     "#dc2626",
    categoria: "infraestructura",
    protocolos: ["wifi", "modbus", "lora"],
    campos:    ["estado", "caudal_lpm", "presion_bar", "horas_uso", "modo"],
    descripcion: "Controla y monitorea bombas de agua.",
  },
  cerca_electrica: {
    nombre:    "Controlador de Cerca Eléctrica",
    icono:     "🔌",
    color:     "#b45309",
    categoria: "infraestructura",
    protocolos: ["wifi", "lora"],
    campos:    ["voltaje_v", "estado", "zona", "energia_j"],
    descripcion: "Controla y programa la cerca eléctrica.",
  },
};

export const DEVICE_STATUS = {
  ONLINE:       "online",
  OFFLINE:      "offline",
  ALERTA:       "alerta",
  MANTENIMIENTO:"mantenimiento",
  CONECTANDO:   "conectando",
  ERROR:        "error",
};

export const DEVICE_STATUS_CONFIG = {
  online:        { label: "En línea",       color: "#16a34a", bg: "#f0fdf4", icono: "🟢" },
  offline:       { label: "Sin conexión",   color: "#6b7280", bg: "#f9fafb", icono: "⚫" },
  alerta:        { label: "Con alerta",     color: "#d97706", bg: "#fffbeb", icono: "🟡" },
  mantenimiento: { label: "Mantenimiento",  color: "#2563eb", bg: "#eff6ff", icono: "🔵" },
  conectando:    { label: "Conectando…",    color: "#7c3aed", bg: "#f5f3ff", icono: "🔄" },
  error:         { label: "Error",          color: "#dc2626", bg: "#fef2f2", icono: "🔴" },
};

export const PROTOCOL_CONFIG = {
  wifi:      { label: "WiFi",      icono: "📶", velocidad: "alta",  rango: "100m" },
  bluetooth: { label: "Bluetooth", icono: "📲", velocidad: "media", rango: "50m"  },
  lora:      { label: "LoRa",      icono: "📡", velocidad: "baja",  rango: "15km" },
  "4g":      { label: "4G/LTE",   icono: "📱", velocidad: "alta",  rango: "ilimitado" },
  "5g":      { label: "5G",        icono: "🚀", velocidad: "alta",  rango: "ilimitado" },
  mqtt:      { label: "MQTT",      icono: "🔗", velocidad: "media", rango: "internet" },
  modbus:    { label: "Modbus",    icono: "🔌", velocidad: "media", rango: "1.2km" },
  zigbee:    { label: "Zigbee",    icono: "📻", velocidad: "baja",  rango: "100m" },
  rs232:     { label: "RS-232",    icono: "🖧",  velocidad: "baja",  rango: "15m"  },
  ethernet:  { label: "Ethernet",  icono: "🔌", velocidad: "alta",  rango: "100m" },
  usb:       { label: "USB",       icono: "🔌", velocidad: "alta",  rango: "5m"   },
};

export const DEVICE_CATEGORIAS = {
  identificacion: { label: "Identificación",    icono: "🏷️" },
  ubicacion:      { label: "Ubicación",          icono: "📍" },
  produccion:     { label: "Producción",         icono: "📊" },
  ambiental:      { label: "Ambiental",          icono: "🌿" },
  infraestructura:{ label: "Infraestructura",    icono: "🏗️" },
  animal:         { label: "Animal",             icono: "🐄" },
  vigilancia:     { label: "Vigilancia",         icono: "👁️" },
  inspeccion:     { label: "Inspección",         icono: "🚁" },
  energia:        { label: "Energía",            icono: "☀️" },
};

export const TIPOS_LISTA = Object.entries(DEVICE_TYPE_CONFIG).map(([id, cfg]) => ({ id, ...cfg }));
