/**
 * Catálogo inicial de cursos predefinidos.
 * El contenido de cada curso se genera bajo demanda por la IA.
 */

export const CURSO_CATALOG = [
  {
    id: "sanidad-basica",
    titulo: "Sanidad Bovina Básica",
    descripcion: "Fundamentos de salud animal: vacunación, desparasitación y manejo preventivo.",
    nivel: "principiante",
    duracionMins: 90,
    categoria: "sanidad",
    especialista: "veterinario",
    icono: "🏥",
    objetivos: ["Identificar enfermedades comunes", "Diseñar calendarios de vacunación", "Aplicar tratamientos preventivos"],
    lecciones: 6,
    popular: true,
  },
  {
    id: "mastitis-control",
    titulo: "Control de Mastitis",
    descripcion: "Diagnóstico, tratamiento y prevención de la mastitis bovina.",
    nivel: "intermedio",
    duracionMins: 60,
    categoria: "sanidad",
    especialista: "veterinario",
    icono: "🔬",
    objetivos: ["Diagnosticar mastitis clínica y subclínica", "Aplicar protocolos de tratamiento", "Implementar prevención"],
    lecciones: 4,
    popular: true,
  },
  {
    id: "nutricion-tropical",
    titulo: "Nutrición en Trópico",
    descripcion: "Alimentación estratégica del ganado en zonas tropicales y subtropicales.",
    nivel: "intermedio",
    duracionMins: 75,
    categoria: "nutricion",
    especialista: "nutricionista",
    icono: "🌿",
    objetivos: ["Calcular requerimientos nutricionales", "Formular raciones balanceadas", "Manejar épocas de sequía"],
    lecciones: 5,
    popular: true,
  },
  {
    id: "reproduccion-fundamentos",
    titulo: "Reproducción Bovina",
    descripcion: "Ciclo reproductivo, detección de celos y manejo de la fertilidad.",
    nivel: "principiante",
    duracionMins: 80,
    categoria: "reproduccion",
    especialista: "reproduccion",
    icono: "🐄",
    objetivos: ["Entender el ciclo estral", "Detectar celos eficientemente", "Calcular índices reproductivos"],
    lecciones: 5,
    popular: true,
  },
  {
    id: "inseminacion-artificial",
    titulo: "Inseminación Artificial",
    descripcion: "Técnicas de IA a tiempo fijo: Ovsynch, Co-Synch y protocolos avanzados.",
    nivel: "avanzado",
    duracionMins: 120,
    categoria: "inseminacion",
    especialista: "reproduccion",
    icono: "🔬",
    objetivos: ["Dominar protocolos de sincronización", "Realizar IA con técnica correcta", "Evaluar tasas de preñez"],
    lecciones: 8,
    popular: false,
  },
  {
    id: "pasturas-rotacion",
    titulo: "Pastoreo Rotacional",
    descripcion: "Diseño e implementación de sistemas de pastoreo rotacional intensivo.",
    nivel: "intermedio",
    duracionMins: 70,
    categoria: "pasturas",
    especialista: "pasturas",
    icono: "🌾",
    objetivos: ["Calcular carga animal", "Diseñar potreros", "Maximizar producción forrajera"],
    lecciones: 5,
    popular: true,
  },
  {
    id: "silvopastoreo-ssp",
    titulo: "Sistemas Silvopastoriles",
    descripcion: "Integración de árboles, pastos y ganado para una ganadería sostenible.",
    nivel: "avanzado",
    duracionMins: 90,
    categoria: "silvopastoreo",
    especialista: "pasturas",
    icono: "🌳",
    objetivos: ["Diseñar un SSP", "Seleccionar especies arbóreas", "Medir beneficios ambientales"],
    lecciones: 6,
    popular: false,
  },
  {
    id: "finanzas-ganaderas",
    titulo: "Finanzas para Ganaderos",
    descripcion: "Costos de producción, punto de equilibrio y rentabilidad ganadera.",
    nivel: "principiante",
    duracionMins: 65,
    categoria: "finanzas",
    especialista: "finanzas",
    icono: "💰",
    objetivos: ["Calcular costos de producción", "Identificar punto de equilibrio", "Mejorar rentabilidad"],
    lecciones: 4,
    popular: true,
  },
  {
    id: "bienestar-cinco-libertades",
    titulo: "Bienestar Animal",
    descripcion: "Las Cinco Libertades y su implementación práctica en la finca.",
    nivel: "principiante",
    duracionMins: 50,
    categoria: "bienestar",
    especialista: "bienestar",
    icono: "❤️",
    objetivos: ["Aplicar las Cinco Libertades", "Evaluar indicadores de bienestar", "Cumplir normativa ICA"],
    lecciones: 4,
    popular: false,
  },
  {
    id: "manejo-terneros",
    titulo: "Manejo de Terneros",
    descripcion: "Calostro, destete, alimentación y sanidad en la etapa de cría.",
    nivel: "principiante",
    duracionMins: 60,
    categoria: "terneros",
    especialista: "veterinario",
    icono: "🐮",
    objetivos: ["Gestionar suministro de calostro", "Controlar enfermedades neonatales", "Planificar el destete"],
    lecciones: 4,
    popular: true,
  },
  {
    id: "genetica-mejoramiento",
    titulo: "Mejoramiento Genético",
    descripcion: "DEPs, selección de reproductores y uso de semen importado.",
    nivel: "avanzado",
    duracionMins: 100,
    categoria: "genetica",
    especialista: "reproduccion",
    icono: "🧬",
    objetivos: ["Interpretar DEPs", "Seleccionar reproductores", "Diseñar cruzamientos"],
    lecciones: 6,
    popular: false,
  },
  {
    id: "corrales-bajo-estres",
    titulo: "Manejo en Corrales sin Estrés",
    descripcion: "Principios de Temple Grandin aplicados al manejo bovino.",
    nivel: "intermedio",
    duracionMins: 55,
    categoria: "corrales",
    especialista: "corrales",
    icono: "🏠",
    objetivos: ["Aplicar manejo bajo estrés", "Diseñar flujos de trabajo seguros", "Reducir lesiones y accidentes"],
    lecciones: 4,
    popular: false,
  },
  {
    id: "leche-calidad",
    titulo: "Calidad de Leche",
    descripcion: "Higiene, enfriamiento, buenas prácticas de ordeño y certificaciones.",
    nivel: "intermedio",
    duracionMins: 70,
    categoria: "leche",
    especialista: "produccion",
    icono: "🥛",
    objetivos: ["Implementar BPO", "Reducir CCS y CBT", "Cumplir normativa lechera"],
    lecciones: 5,
    popular: true,
  },
  {
    id: "carne-engorde",
    titulo: "Producción de Carne",
    descripcion: "Engorde intensivo, semi-intensivo y en pastoreo: estrategias y rentabilidad.",
    nivel: "intermedio",
    duracionMins: 80,
    categoria: "carne",
    especialista: "produccion",
    icono: "🥩",
    objetivos: ["Calcular GMD objetivo", "Diseñar dietas de engorde", "Maximizar conversión alimenticia"],
    lecciones: 5,
    popular: false,
  },
  {
    id: "infraestructura-finca",
    titulo: "Infraestructura Ganadera",
    descripcion: "Corrales, salas de ordeño, agua, energía solar y cercas eléctricas.",
    nivel: "principiante",
    duracionMins: 75,
    categoria: "infraestructura",
    especialista: "infraestructura",
    icono: "🏗️",
    objetivos: ["Diseñar corrales funcionales", "Dimensionar sistemas de agua", "Planificar energía solar"],
    lecciones: 5,
    popular: false,
  },
  {
    id: "ia-ganadera",
    titulo: "IA aplicada a la Ganadería",
    descripcion: "Cómo usar inteligencia artificial para tomar mejores decisiones en tu finca.",
    nivel: "principiante",
    duracionMins: 45,
    categoria: "inteligencia_ia",
    especialista: null,
    icono: "🤖",
    objetivos: ["Usar la IA para diagnóstico", "Generar reportes automáticos", "Tomar decisiones basadas en datos"],
    lecciones: 3,
    popular: true,
  },
  {
    id: "administracion-finca",
    titulo: "Administración de la Finca",
    descripcion: "Registros, indicadores clave y gestión del equipo de trabajo.",
    nivel: "principiante",
    duracionMins: 60,
    categoria: "administracion",
    especialista: "finanzas",
    icono: "📊",
    objetivos: ["Implementar registros básicos", "Calcular KPIs ganaderos", "Gestionar el personal"],
    lecciones: 4,
    popular: false,
  },
  {
    id: "parasitologia-bovinos",
    titulo: "Parasitología Bovina",
    descripcion: "Ectoparásitos, endoparásitos y estrategias de control integrado.",
    nivel: "intermedio",
    duracionMins: 65,
    categoria: "sanidad",
    especialista: "veterinario",
    icono: "🦠",
    objetivos: ["Identificar principales parásitos", "Diseñar rotación de antiparasitarios", "Reducir resistencia"],
    lecciones: 4,
    popular: false,
  },
  {
    id: "transferencia-embriones",
    titulo: "Transferencia de Embriones",
    descripcion: "Superovulación, colecta, evaluación y transferencia de embriones bovinos.",
    nivel: "experto",
    duracionMins: 150,
    categoria: "embriones",
    especialista: "reproduccion",
    icono: "🧫",
    objetivos: ["Aplicar protocolos de superovulación", "Evaluar embriones bajo microscopio", "Realizar transferencia fresca y congelada"],
    lecciones: 10,
    popular: false,
  },
  {
    id: "enfermedades-metabolicas",
    titulo: "Enfermedades Metabólicas",
    descripcion: "Hipocalcemia, cetosis, acidosis y laminitis: prevención y tratamiento.",
    nivel: "avanzado",
    duracionMins: 70,
    categoria: "sanidad",
    especialista: "veterinario",
    icono: "⚗️",
    objetivos: ["Prevenir el síndrome de la vaca caída", "Manejar la cetosis posparto", "Controlar la acidosis ruminal"],
    lecciones: 5,
    popular: false,
  },
];

export function getCursoById(id) {
  return CURSO_CATALOG.find(c => c.id === id) ?? null;
}

export function getCursosByCategoria(categoria) {
  return CURSO_CATALOG.filter(c => c.categoria === categoria);
}

export function getCursosPopulares() {
  return CURSO_CATALOG.filter(c => c.popular);
}
