/**
 * Simuladores educativos de la Academia Ganadera.
 * Cada simulador es un escenario interactivo con pasos guiados por IA.
 */

export const SIMULADORES = [
  {
    id: "sim-parto",
    titulo: "Simulación de Parto Bovino",
    descripcion: "Aprende a identificar las etapas del parto, cuándo intervenir y cómo asistir un parto complicado.",
    icono: "🐣",
    categoria: "sanidad",
    nivel: "intermedio",
    duracionMins: 20,
    pasos: [
      "Identificación de los signos preparto",
      "Evaluación de la presentación del ternero",
      "Determinación del momento de intervención",
      "Técnicas de tracción obstétrica",
      "Atención al ternero recién nacido",
      "Cuidados posparto de la vaca",
    ],
    promptBase: "Simula interactivamente el proceso de un parto bovino. Presenta cada etapa con detalles clínicos reales, haz preguntas al estudiante y evalúa sus respuestas.",
  },
  {
    id: "sim-vacunacion",
    titulo: "Simulación de Vacunación",
    descripcion: "Practica el protocolo completo de vacunación: preparación, técnica y registro.",
    icono: "💉",
    categoria: "sanidad",
    nivel: "principiante",
    duracionMins: 15,
    pasos: [
      "Revisión del plan sanitario",
      "Preparación de materiales y vacunas",
      "Evaluación del animal antes de vacunar",
      "Técnica de aplicación subcutánea e intramuscular",
      "Registro y trazabilidad",
      "Manejo de reacciones adversas",
    ],
    promptBase: "Simula el proceso de vacunación bovina paso a paso. Presenta cada etapa, incluye preguntas de decisión clínica y retroalimentación inmediata.",
  },
  {
    id: "sim-inseminacion",
    titulo: "Simulación de Inseminación Artificial",
    descripcion: "Aprende la técnica de inseminación artificial a tiempo fijo desde la preparación del semen hasta la aplicación.",
    icono: "🔬",
    categoria: "inseminacion",
    nivel: "avanzado",
    duracionMins: 25,
    pasos: [
      "Evaluación reproductiva de la vaca",
      "Sincronización hormonal (Ovsynch)",
      "Descongelamiento correcto del semen",
      "Evaluación de la motilidad espermática",
      "Técnica de deposición intrauterina",
      "Diagnóstico de preñez a los 30 días",
    ],
    promptBase: "Guía al estudiante por una inseminación artificial completa. Presenta decisiones técnicas críticas, consecuencias de errores y retroalimentación experta.",
  },
  {
    id: "sim-enfermedad",
    titulo: "Brote de Enfermedad",
    descripcion: "Maneja un brote de enfermedad en tu hato: diagnóstico, cuarentena, tratamiento y prevención.",
    icono: "🚨",
    categoria: "sanidad",
    nivel: "avanzado",
    duracionMins: 30,
    pasos: [
      "Detección del primer animal enfermo",
      "Evaluación clínica y diagnóstico diferencial",
      "Decisión de cuarentena y aislamiento",
      "Protocolo de tratamiento",
      "Notificación a autoridades (si aplica)",
      "Prevención de diseminación",
      "Revisión del protocolo sanitario",
    ],
    promptBase: "Presenta un escenario de brote de enfermedad bovina. Haz que el estudiante tome decisiones críticas en tiempo real con consecuencias realistas.",
  },
  {
    id: "sim-rotacion-potreros",
    titulo: "Rotación de Potreros",
    descripcion: "Diseña y gestiona un sistema de pastoreo rotacional para optimizar la producción forrajera.",
    icono: "🗺️",
    categoria: "pasturas",
    nivel: "intermedio",
    duracionMins: 20,
    pasos: [
      "Evaluación del área disponible",
      "Cálculo de la carga animal",
      "División en potreros",
      "Estimación del período de ocupación",
      "Monitoreo del rebrote forrajero",
      "Ajuste de la rotación en verano",
    ],
    promptBase: "Simula la gestión de un sistema de pastoreo rotacional con datos reales. Presenta cálculos, decisiones de manejo y consecuencias de cada decisión.",
  },
  {
    id: "sim-palpacion",
    titulo: "Diagnóstico de Gestación",
    descripcion: "Aprende a diagnosticar preñez por palpación rectal e interpretación de ultrasonido.",
    icono: "🔭",
    categoria: "reproduccion",
    nivel: "avanzado",
    duracionMins: 20,
    pasos: [
      "Criterios para realizar el diagnóstico",
      "Técnica de palpación rectal segura",
      "Identificación de estructuras uterinas",
      "Estimación de días de gestación",
      "Interpretación de ultrasonido",
      "Registro y decisiones de manejo",
    ],
    promptBase: "Simula el proceso de diagnóstico de gestación en bovinos. Presenta hallazgos clínicos descriptivos y evalúa las decisiones del estudiante.",
  },
  {
    id: "sim-financiero",
    titulo: "Simulación Financiera",
    descripcion: "Toma decisiones financieras clave en tu finca y observa el impacto en la rentabilidad.",
    icono: "💰",
    categoria: "finanzas",
    nivel: "intermedio",
    duracionMins: 25,
    pasos: [
      "Análisis del estado financiero actual",
      "Identificación de costos controlables",
      "Evaluación de una inversión",
      "Cálculo del retorno esperado",
      "Gestión del flujo de caja",
      "Plan de mejora financiera",
    ],
    promptBase: "Presenta un escenario financiero ganadero con datos numéricos reales. Guía al estudiante por decisiones de inversión, costos y rentabilidad con cálculos paso a paso.",
  },
];

export function getSimuladorById(id) {
  return SIMULADORES.find(s => s.id === id) ?? null;
}
